# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: vecino
email: info@vecino.com.co
description: > # this means to ignore newlines until "baseurl:"
  IMPLEMENTA TU IDEA DE NEGOCIO
  Desarrollo Ágil, Modelos de Negocio, Estrategia de Mercadeo Digital
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.vecino.com.co" # the base hostname & protocol for your site
twitter_username: vecino_tw
github_username: veci

# Build settings
markdown: kramdown
